services:
  dhcp-server:
    environment:
      DHCPV6_INTERFACE_ID_POLICY: 1
      DHCPV6_INTERFACE_ID_A_HEX: ${DHCPV6_INTERFACE_ID_A_HEX:-00ff706f72742d418000}
      DHCPV6_INTERFACE_ID_B_HEX: ${DHCPV6_INTERFACE_ID_B_HEX:-817669662d42007f}
      DHCPV6_INTERFACE_ID_POOL_A: ${DHCPV6_INTERFACE_ID_POOL_A:-fd00:29::100 - fd00:29::17f}
      DHCPV6_INTERFACE_ID_POOL_B: ${DHCPV6_INTERFACE_ID_POOL_B:-fd00:29::180 - fd00:29::1ff}

  test-runner:
    environment:
      TEST_CAPABILITIES: ${TEST_CAPABILITIES:-dhcpv6_interface_id_policy}
      TEST_DHCPV6_INTERFACE_ID_A_HEX: ${DHCPV6_INTERFACE_ID_A_HEX:-00ff706f72742d418000}
      TEST_DHCPV6_INTERFACE_ID_B_HEX: ${DHCPV6_INTERFACE_ID_B_HEX:-817669662d42007f}
      TEST_DHCPV6_INTERFACE_ID_POOL_A_START: fd00:29::100
      TEST_DHCPV6_INTERFACE_ID_POOL_A_END: fd00:29::17f
      TEST_DHCPV6_INTERFACE_ID_POOL_B_START: fd00:29::180
      TEST_DHCPV6_INTERFACE_ID_POOL_B_END: fd00:29::1ff
