services:
  dhcp-server:
    environment:
      RFC3011_ALT_SUBNET: 172.29.16.0/20
      RFC3011_ALT_SERVER_IP: 172.29.16.2
      DHCPV4_RELAY_SUBNET: 172.29.32.0/20
      DHCPV4_POOL_START_ADDRESS: ${DHCPV4_POOL_START_ADDRESS:-}
      DHCPV4_POOL_END_ADDRESS: ${DHCPV4_POOL_END_ADDRESS:-}
      DHCPV4_ALT_POOL_ENABLED: 0

  test-runner:
    environment:
      TEST_DHCPV4_CAPACITY_POOL_START: ${DHCPV4_POOL_START_ADDRESS:-}
      TEST_DHCPV4_CAPACITY_POOL_END: ${DHCPV4_POOL_END_ADDRESS:-}
      TEST_DHCPV4_LOAD_CAPTURE_TIMEOUT: ${TEST_DHCPV4_CAPACITY_CAPTURE_TIMEOUT:-15}
      DHCPV4_ALT_POOL_ENABLED: 0

networks:
  dhcp-test-net:
    ipam:
      config:
        - subnet: 172.29.0.0/20
