"""Render the human-readable RFC requirements matrix from its CSV source."""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parent
MATRIX = ROOT / "docs" / "rfc-requirements.csv"
DOCUMENT = ROOT / "docs" / "RFC_REQUIREMENTS.md"

RFC_TITLES = {
    "2131": "Dynamic Host Configuration Protocol",
    "2132": "DHCP Options and BOOTP Vendor Extensions",
    "3011": "IPv4 Subnet Selection Option",
    "3046": "DHCP Relay Agent Information Option",
    "3396": "Encoding Long DHCP Options",
    "3442": "Classless Static Route Option",
    "4361": "Node-specific Client Identifiers for DHCPv4",
    "4702": "DHCP Client FQDN Option",
    "4704": "DHCPv6 Client FQDN Option",
    "6842": "Client Identifier Option in DHCP Server Replies",
    "8925": "IPv6-Only Preferred Option for DHCPv4",
    "9915": "Dynamic Host Configuration Protocol for IPv6",
}

STATUSES = ("covered", "partial", "conditional", "gap", "excluded")


def read_rows() -> list[dict[str, str]]:
    with MATRIX.open(newline="", encoding="utf-8") as matrix_file:
        return list(csv.DictReader(matrix_file))


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _evidence(value: str) -> str:
    if not value:
        return "—"
    rendered = []
    for item in value.split(";"):
        path, scenario = item.split("::", 1)
        rendered.append(f"[{_escape(scenario)}](../{path})")
    return "<br>".join(rendered)


def render_matrix(rows: list[dict[str, str]] | None = None) -> str:
    rows = read_rows() if rows is None else rows
    counts = Counter(row["status"] for row in rows)

    lines = [
        "# RFC MUST/SHOULD traceability matrix",
        "",
        "This document is generated from [`rfc-requirements.csv`](rfc-requirements.csv).",
        "Edit the CSV and run `python render_rfc_requirements.py`; do not edit this file directly.",
        "",
        "The matrix maps acceptance-relevant normative requirements for the DHCP server role to",
        "executable scenarios. `MUST` also represents RFC `SHALL`; `SHOULD` also represents",
        "`RECOMMENDED`. Requirement text is deliberately paraphrased—use the linked RFC section",
        "as the authoritative statement.",
        "",
        "This is a maintained coverage matrix, not a blanket compliance certificate. A `covered`",
        "row means the named scenario directly asserts the requirement in the reference fixture.",
        "`partial` means only part of the clause is asserted, `conditional` requires a capability",
        "adapter, `gap` has no adequate assertion, and `excluded` records a reviewed non-applicable",
        "requirement. Product-specific applicability review is still required.",
        "",
        "## Summary",
        "",
        "| Requirements | Covered | Partial | Conditional | Gap | Excluded |",
        "|---:|---:|---:|---:|---:|---:|",
        (
            f"| {len(rows)} | {counts['covered']} | {counts['partial']} | "
            f"{counts['conditional']} | {counts['gap']} | {counts['excluded']} |"
        ),
        "",
        "| RFC | Title | Requirements | Covered | Partial | Conditional | Gap | Excluded |",
        "|---:|---|---:|---:|---:|---:|---:|---:|",
    ]

    for number, title in RFC_TITLES.items():
        rfc_rows = [row for row in rows if row["rfc"] == number]
        rfc_counts = Counter(row["status"] for row in rfc_rows)
        source = f"https://www.rfc-editor.org/rfc/rfc{number}.html"
        lines.append(
            f"| [{number}]({source}) | {title} | {len(rfc_rows)} | "
            f"{rfc_counts['covered']} | {rfc_counts['partial']} | "
            f"{rfc_counts['conditional']} | {rfc_counts['gap']} | "
            f"{rfc_counts['excluded']} |"
        )

    for number, title in RFC_TITLES.items():
        rfc_rows = [row for row in rows if row["rfc"] == number]
        lines.extend(
            [
                "",
                f"## RFC {number}: {title}",
                "",
                "| ID | Section | Level | Status | Requirement | Evidence / rationale |",
                "|---|---:|---|---|---|---|",
            ]
        )
        for row in rfc_rows:
            section_url = (
                f"https://www.rfc-editor.org/rfc/rfc{number}.html#section-{row['section']}"
            )
            evidence = _evidence(row["evidence"])
            if row["notes"]:
                note = _escape(row["notes"])
                evidence = f"{evidence}<br>{note}" if evidence != "—" else note
            lines.append(
                f"| `{row['requirement_id']}` | [{row['section']}]({section_url}) | "
                f"{row['level']} | **{row['status']}** | {_escape(row['requirement'])} | "
                f"{evidence} |"
            )

    lines.extend(
        [
            "",
            "## Claim boundary",
            "",
            "The CSV is a curated inventory of server requirements that are relevant to the",
            "behaviors claimed by this repository. Client-only behavior, relay-agent implementation",
            "internals, protocol-management requirements, and optional functions not advertised by",
            "the target are outside the default server claim. The open `gap`, `partial`, and",
            "unexecuted `conditional` rows prevent a full-RFC compliance claim.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    DOCUMENT.write_text(render_matrix(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
